#!/usr/bin/env python3
"""Plot threshold curves and a latency/accuracy Pareto front for MoE pruning."""

from __future__ import annotations

import argparse
import csv
from pathlib import Path


def read_rows(csv_path: Path) -> list[dict[str, str]]:
    with csv_path.open(newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def as_float(row: dict[str, str], key: str) -> float | None:
    value = row.get(key, "")
    if value == "":
        return None
    try:
        return float(value)
    except ValueError:
        return None


def pareto_front(rows: list[dict[str, str]]) -> list[dict[str, str]]:
    scored = [r for r in rows if as_float(r, "latency_ms") is not None and as_float(r, "mAP50-95") is not None]
    scored.sort(key=lambda r: (as_float(r, "latency_ms") or 0.0, -(as_float(r, "mAP50-95") or 0.0)))
    front: list[dict[str, str]] = []
    best_map = -1.0
    for row in scored:
        map_val = as_float(row, "mAP50-95") or 0.0
        if map_val > best_map:
            front.append(row)
            best_map = map_val
    return front


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("csv", type=Path, help="CSV generated by scripts/moe_pruning_sweep.py and filled with metrics.")
    parser.add_argument("--out-dir", type=Path, help="Output directory for plots. Defaults to CSV parent.")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    rows = read_rows(args.csv)
    out_dir = args.out_dir or args.csv.parent
    out_dir.mkdir(parents=True, exist_ok=True)

    try:
        import matplotlib.pyplot as plt
    except Exception as exc:
        print(f"[plot] matplotlib unavailable: {exc}")
        return 1

    metric_keys = ("mAP50-95", "gflops", "latency_ms")
    for metric in metric_keys:
        usable = [r for r in rows if as_float(r, "threshold") is not None and as_float(r, metric) is not None]
        if not usable:
            print(f"[plot] skip {metric}: no numeric values")
            continue
        plt.figure(figsize=(7, 4))
        for recovery in sorted({r["recovery"] for r in usable}):
            group = [r for r in usable if r["recovery"] == recovery]
            group.sort(key=lambda r: as_float(r, "threshold") or 0.0)
            plt.plot(
                [as_float(r, "threshold") for r in group],
                [as_float(r, metric) for r in group],
                marker="o",
                label=recovery,
            )
        plt.xlabel("Pruning threshold")
        plt.ylabel(metric)
        plt.grid(True, alpha=0.3)
        plt.legend()
        plt.tight_layout()
        out = out_dir / f"threshold_{metric.replace('/', '_')}.png"
        plt.savefig(out, dpi=160)
        plt.close()
        print(f"[plot] wrote {out}")

    front = pareto_front(rows)
    if front:
        plt.figure(figsize=(6, 5))
        for row in rows:
            x = as_float(row, "latency_ms")
            y = as_float(row, "mAP50-95")
            if x is None or y is None:
                continue
            plt.scatter(x, y, alpha=0.6)
            plt.text(x, y, f"{row['threshold']}/{row['recovery']}", fontsize=8)
        plt.plot([as_float(r, "latency_ms") for r in front], [as_float(r, "mAP50-95") for r in front], linewidth=2)
        sweet = max(front, key=lambda r: (as_float(r, "mAP50-95") or 0.0) / max(as_float(r, "latency_ms") or 1.0, 1e-6))
        plt.scatter([as_float(sweet, "latency_ms")], [as_float(sweet, "mAP50-95")], s=120, marker="*", label="sweet spot")
        plt.xlabel("Latency (ms)")
        plt.ylabel("mAP50-95")
        plt.grid(True, alpha=0.3)
        plt.legend()
        plt.tight_layout()
        out = out_dir / "pareto_accuracy_latency.png"
        plt.savefig(out, dpi=160)
        plt.close()
        print(f"[plot] wrote {out}")
        print(f"[plot] sweet spot: threshold={sweet['threshold']} recovery={sweet['recovery']}")
    else:
        print("[plot] skip pareto: need numeric latency_ms and mAP50-95")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
